[package]
name = "keycrate-full-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sysinfo = "0.30"
chrono = { version = "0.4", features = ["serde"] }
md5 = "0.7"
keycrate = "1.0.0"
serde_json = "1.0"
sha2 = "0.10"
